---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmware-explore-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app-ui
      tier: frontend
  template:
    metadata:
      labels:
        app: demo-app-ui
        tier: frontend
    spec:
      containers:
        - name: demo-app-ui
          image: ghcr.io/beyondelastic/vmware-explore-app:v7
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: vmware-explore-app
  labels:
    app: demo-app-ui
    tier: frontend
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: demo-app-ui
    tier: frontend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vmworld-demo-app
spec:
  rules:
  - host: vmworld.apps.cpod-nsxv8.az-stc.cloud-garage.net
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: vmware-explore-app
            port:
              number: 80
